name: Auto Update README Version

on:
  push:
    tags:
      - 'release/*/v*'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - run: bun install
      
      - id: tag
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          MODULE_NAME=$(echo $TAG_NAME | cut -d'/' -f2)
          VERSION=$(echo $TAG_NAME | cut -d'/' -f3 | sed 's/^v//')
          
          echo "MODULE_NAME=$MODULE_NAME" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT
      
      - id: check
        run: |
          chmod +x ./update-version.sh
          if ./update-version.sh --check "${{ steps.tag.outputs.MODULE_NAME }}" "${{ steps.tag.outputs.VERSION }}"; then
            echo "NEEDS_UPDATE=false" >> $GITHUB_OUTPUT
          else
            echo "NEEDS_UPDATE=true" >> $GITHUB_OUTPUT
          fi
      
      - if: steps.check.outputs.NEEDS_UPDATE == 'true'
        run: |
          git config user.name "cdrci"
          git config user.email "cdrci@users.noreply.github.com"
          chmod +x ./update-version.sh
          ./update-version.sh "${{ steps.tag.outputs.MODULE_NAME }}" "${{ steps.tag.outputs.VERSION }}"
      
      - if: steps.check.outputs.NEEDS_UPDATE == 'true'
        id: create-pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          MODULE="${{ steps.tag.outputs.MODULE_NAME }}"
          VERSION="${{ steps.tag.outputs.VERSION }}"
          BRANCH="automated-update-$MODULE-$VERSION"
          PR_TITLE="chore: update $MODULE version to $VERSION"
          
          git checkout -b "$BRANCH"
          git add "$MODULE/README.md"
          git commit -m "$PR_TITLE"
          git push origin "$BRANCH"
          
          PR_URL=$(gh pr create \
            --title "$PR_TITLE" \
            --body "Updates README version to match tag ${{ steps.tag.outputs.TAG_NAME }}" \
            --base main \
            --head "$BRANCH")
          
          PR_NUMBER=$(echo "$PR_URL" | grep -o '[0-9]*$')
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          
          gh pr merge "$PR_NUMBER" --auto --squash
      
      - if: steps.create-pr.outputs.pr_number
        uses: hmarr/auto-approve-action@v3
        with:
          pull-request-number: ${{ steps.create-pr.outputs.pr_number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}